### ISSUE TITLE
Code README

### ISSUE THREAD

**Issue by sternlis** [joscha-st/bad_walden_stadtwerke#53]

**Comment by joscha-st** [comment]
Add architecture info to add information about the use of a server with web endpoints via an API for the external backend incl database

**Comment by joscha-st** [comment]
add info to file structure: The actual module can be found in /Code/Bwstadtwerke, wich contains code and resources

**Comment by joscha-st** [comment]
add info about use of 
- maven
- java FXML
- Restrictive use of dependencies
-

**Comment by joscha-st** [comment]
javaFXML is not a programming language

**Comment by joscha-st** [comment]
Info: Further expansion must be to load a state into the signup process. As data is saved on the server to minimize data loss, this shoud also be reloaded when signing up again. We were not able to hadle this due to time constrains

**Comment by joscha-st** [comment]
Codestyle / Conventions should be implemented

**Comment by sternlis** [comment]
- benutzen mischung aus javafx und javafxml

**Comment by ArchibaldTheFirst** [comment]
- [ ] Benutzung mischung aus javafx und javafxml
- [ ] codestyle/Conventions should be explained (CamelCase, this use, javadoc usw.)
- [ ] Info: Further expansion must be to load a state into the signup process. As data is saved on the server to minimize data loss, this shoud also be reloaded when signing up again. We were not able to hadle this due to time constrains
- [ ] javaFXML is not a programming language --> more suitable than javaFX
--> make explanation of FXML controller more clear
- [ ] add info to file structure: The actual module can be found in /Code/Bwstadtwerke, wich contains code and resources
- [ ] in the resources folder there is no code, only resources
- [ ] link test folder
- [ ] add info about use of,  maven, java FXML, Restrictive use of dependencies
- [ ] Add architecture info to add information about the use of a server with web endpoints via an API for the external backend incl database

**Comment by ArchibaldTheFirst** [comment]
Done
